### ISSUE TITLE
Integration with Slicer

### ISSUE THREAD

**Issue by jcfr** [blowekamp/Slicer-SimpleFilters#2]
# Home for the Customized SimpleITK Filter description

Repository: https://github.com/Slicer/SimpleITKFilterDescriptions

1) I just pushed a script (based on the work of Brad King and Kent Williams) allowing to semi-automatically update the SimpleITK description files customized for Slicer usage.

2) You can try the script directly without having to modify it, and it will create a branch "update-sitk" that you could directly merge to master.

3) Based on my understanding, some of the script have to be excluded and some other have to be tweaked. 

The exclusion of filter description could be done by further customizing the script "UpdateFilterDescriptionsFromSimpleITK.sh" at line 63 [1].

The tweaking could be done by adding further commit to the topic "update-sitk"

4) You have now push/pull access to that repository.

[1] https://github.com/Slicer/SimpleITKFilterDescriptions/blob/b2980ff3a27b45d5721caf3514ab4f701af92319/UpdateFilterDescriptionsFromSimpleITK.sh#L63
# Integration with Slicer

I would suggest the following approach:

Add two external project:

1) External project "SimpleITKFilterDescriptions" that would checkout the source of the corresponding project. A variable SimpleITKFilterDescriptions_DIR would be then available for any module willing to use these filters.

2) External project "SimpleFiltersModule" that would checkout the source of the corresponding project and add it to Slicer similarly to what is done for MultiVolumeExplorer project.
# Performance consideration regarding loading of description files

The json files could be bundled as a Qt resources. This could be done by creating a file named Base/QTCore/Resources/SimpleITKFilterDescriptions.qrc that would be "compiled" into the Slicer BaseQTCore library. The file would then be available using a construct like:

qt.QFile(":/SimpleITKFilterDescriptions/BasicFilers/json/foo.json")

Let me know if you any other questions, 
Jc

**Comment by blowekamp** [comment]
The repository has been moved to: https://github.com/SimpleITK/SlicerSimpleFilters

This module has been integrated as an internal module into Slicer3D's main repo. This new repo as an sitk-upstream branch to contain the json files from SimpleITK and to use subtree merge into the repo.

The issue of reducing the number of json files still exists.
